apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ic-devops
  name: ic-deploy-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-devops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ic-devops
    spec:
      volumes:
      - name: ic-volume-devops
        emptyDir: {}

      containers:
      - image: debian:latest
        name: ic-main-devops
        command: ['/bin/bash','-c','while true; do cat /ic/ecommerce; sleep 5; done']
        volumeMounts:
        - mountPath: /ic
          name: ic-volume-devops

      initContainers:
      - name: ic-msg-devops
        image: debian:latest
        command: ['/bin/bash','-c','echo Init Done - Welcome to xFusionCorp Industries > /ic/ecommerce']
        volumeMounts:
        - mountPath: /ic
          name: ic-volume-devops


status: {}
