apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-service
  name: nginx-service
spec:
  ports:
  - name: 80-80
    nodePort: 30011
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
    type: front-end
  type: NodePort
status:
  loadBalancer: {}
