apiVersion: v1
data:
  beta.txt: NWVjdXIzIQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: beta


---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-xfusion
  name: secret-xfusion
spec:
  containers:
  - command: ['/bin/bash', '-c','sleep 10000']
    image: centos:latest
    name: secret-container-xfusion
    volumeMounts:
    - name: secret-volume-xfusion
      mountPath: "/opt/apps"
      readOnly: true
  volumes:
  - name: secret-volume-xfusion
    secret:
      secretName: beta
      # defaultMode: 0400