
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-xfusion
spec:
  capacity:
    storage: 7Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/dba
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kodekloud-control-plane

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-xfusion
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-xfusion
  label:  
    app: web-xfusion
spec:
  volumes:
    - name: storage-xfusion
      persistentVolumeClaim:
        claimName:  pvc-xfusion
  containers:
    - name: container-xfusion
      image: nginx:latest
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: storage-xfusion


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-xfusion
  name: web-xfusion
spec:
  ports:
  - name: "80"
    nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-xfusion
  type: NodePort
status:
  loadBalancer: {}