apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-cluster-service
  name: redis-cluster-service
spec:
  ports:
  - name: "client"
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: "gossip"
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    app: redis-cluster
  type: ClusterIP
status:
  loadBalancer: {}
