apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-cluster-service
  name: redis-cluster-service
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cluster-service
  type: ClusterIP
status:
  loadBalancer: {}
