apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: countdown-datacenter
  name: countdown-datacenter
  namespace: default
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: countdown-datacenter
      name: countdown-datacenter
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - for i in 10 9 8 7 6 5 4 3 2 1 ; do echo $i ; done
        image: ubuntu:latest
        imagePullPolicy: Always
        name: container-countdown-datacenter
        resources: {}
      restartPolicy: Never
