apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-replicationcontroller
spec:
  replicas: 3
  selector:
    app: httpd_app
  template:
    metadata:
      name: httpd-replicationcontroller
      labels:
        app: httpd_app
        type: front-end
    spec:
      containers:
      - name: httpd-container 
        image: httpd:latest