apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: volume-share-nautilus
  name: volume-share-nautilus
spec:
  volumes:
  - name: volume-share
    emptyDir: {}
  containers:
  - command: ["/bin/bash"]
    args: ["-c","sleep 10000"]
    image: ubuntu:latest
    name: volume-container-nautilus-1
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/news

  - command: ["/bin/bash"]
    args: ["-c","sleep 10000"]
    image: ubuntu:latest
    name: volume-container-nautilus-2
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/apps

