apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: devops
spec: {}
status: {}
---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: devops
  labels:
    run: time-check
  name: time-check
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - image: busybox:latest
    name: time-check-container 
    resources: {}
    command: ['sh','-c',' while true; do date; sleep $TIME_FREQ;done | tee -a  /opt/sysops/time/time-check.log']
    volumeMounts:
    - name: log-volume
      mountPath: "/opt/sysops/time/"
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef: 
          name: time-config     
          key: TIME_FREQ

---
apiVersion: v1
data:
  TIME_FREQ: "6"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: time-config
  namespace: devops

