
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: node-namespace-datacenter
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-deployment-datacenter
  name: node-deployment-datacenter
  namespace: node-namespace-datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-deployment-datacenter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-deployment-datacenter
    spec:
      containers:
      - image: gcr.io/kodekloud/centos-ssh-enabled:node
        name: node-container-datacenter
        ports:
        - containerPort: 80
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-service-datacenter
  name: node-service-datacenter
  namespace: node-namespace-datacenter
spec:
  ports:
  - name: "80"
    nodePort: 30012
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-deployment-datacenter
  type: NodePort
status:
  loadBalancer: {}




